language: node_js
cache: yarn
sudo: false
notifications:
  email: false
node_js:
  - '9'
before_script:
  - yarn lint
after_success:
  - test $TRAVIS_BRANCH = "master" && ./scripts/publish.sh
env:
  global:
    secure: ADMhSwSHVRhDT9/Ds0ssiQkGbP3Vv9gbX2ftCdbJJWB2VUj2tXIIdf6U/0NA2pA2BjtXdut93oDG510ZnsOF1YYZ4Hkd3JmSvZVGXuzwaReiRiIbp2Up7bxq9V3xgwi2GEF7Vb4T2j3P0yYP3udXtspRoDIQADGet8be+5m8rS6lLHc1IayM3dL77/QewWFcW0wJJOer9cdAZN7dJV7jko+3ZyEcAt6L//KsU9+JznMZJuR31N6paGMaje2WYJZiuGnoBCdt0V7AIZvDV9qrOMyde/exkV4iznnkqVZcq1hrcDY+UzZ2V3bd6qBbkr29cbXX44o61VeQmFDA8dqAbdShB6Kzk3bsEVeiq6Af68TjjSHluM9PH5YdVDIGkzT5vwikBVuE3OqiQNf36HCHL9L+67WGaenD7CffNNQ/kmMyFv2lXNjRuxdX8MlTq18ZG+0gLaMZG1Vjj0waPmGOCjqZWwdFNSr53ZpbX28DNG2gN4IkrJ3EvzZAZuM+amBHqJnhKOZk/cJLm8KE8EFWeO1NkckaZXks4n2nDY1SM9jzxkG8xKzXmnfl8ESDdWYnR+MZXM6dcuJxRLwJjOjxQiXEs0qPvHQaz/2tBf50NLKXf5rVUhA448uXnsQ1JGbU7ANKnarsFXi167zTbY68J4DuOw0jVIOt4ru6mRUp/yM=
